name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [lexer, parser, semantic, codegen]

    steps:
      - uses: actions/checkout@v7

      - name: Install spim
        if: matrix.tag == 'codegen'
        run: sudo apt-get update && sudo apt-get install -y spim

      - name: Setup uv
        uses: astral-sh/setup-uv@v9
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups --all-extras

      - name: Run tests
        run: |
          cd src
          make clean
          make
          make test TAG=${{ matrix.tag }}
